using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Europa.TerrorSpider;

//
// License-Identifier: MIT
//

[GenerateTypedNameReferences]
public sealed partial class EggsLayingMenu : RadialMenu
{
    [Dependency] private readonly EntityManager _entManager = default!;

    private SpriteSystem? _sprite;

    public event Action<EntProtoId>? EggChosen;

    public EggsLayingMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _sprite = _entManager.System<SpriteSystem>();

        Refresh();
        Open();
    }

    public void Refresh()
    {
        var main = FindControl<RadialContainer>("Main");

//        AddButton(main, "Queen", _sprite.GetPrototypeIcon("MobTerrorSpiderQueen").TextureFor(Direction.South), "TerrorSpiderEggQueen");
//        AddButton(main, "Mother", _sprite.GetPrototypeIcon("MobTerrorSpiderMother").TextureFor(Direction.South), "TerrorSpiderEggMother");
//        AddButton(main, "Princess", _sprite.GetPrototypeIcon("MobTerrorSpiderPrincess").TextureFor(Direction.South), "TerrorSpiderEggPrincess");
//        AddButton(main, "Prince", _sprite.GetPrototypeIcon("MobTerrorSpiderPrince").TextureFor(Direction.South), "TerrorSpiderEggPrince");
        AddButton(main, "Destroyer", _sprite!.GetPrototypeIcon("MobTerrorSpiderDestroyer").TextureFor(Direction.South), "TerrorSpiderEggDestroyer");
        AddButton(main, "Guardian", _sprite.GetPrototypeIcon("MobTerrorSpiderGuardian").TextureFor(Direction.South), "TerrorSpiderEggGuardian");
        AddButton(main, "Defiler", _sprite.GetPrototypeIcon("MobTerrorSpiderDefiler").TextureFor(Direction.South), "TerrorSpiderEggDefiler");
        AddButton(main, "Widow", _sprite.GetPrototypeIcon("MobTerrorSpiderWidow").TextureFor(Direction.South), "TerrorSpiderEggWidow");
        AddButton(main, "Reaper", _sprite.GetPrototypeIcon("MobTerrorSpiderReaper").TextureFor(Direction.South), "TerrorSpiderEggReaper");
        AddButton(main, "Drone", _sprite.GetPrototypeIcon("MobTerrorSpiderDrone").TextureFor(Direction.South), "TerrorSpiderEggDrone");
        AddButton(main, "Healer", _sprite.GetPrototypeIcon("MobTerrorSpiderHealer").TextureFor(Direction.South), "TerrorSpiderEggHealer");
        AddButton(main, "Lurker", _sprite.GetPrototypeIcon("MobTerrorSpiderLurker").TextureFor(Direction.South), "TerrorSpiderEggLurker");
        AddButton(main, "Knight", _sprite.GetPrototypeIcon("MobTerrorSpiderKnight").TextureFor(Direction.South), "TerrorSpiderEggKnight");
    }

    private void AddButton(RadialContainer main, string tooltip, Texture sprite, string prototype)
    {
        var button = new MenuButton()
        {
            StyleClasses = { "RadialMenuButton" },
            SetSize = new Vector2(64f, 64f),
            ToolTip = tooltip,
        };

        var tex = new TextureRect()
        {
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Center,
            Texture = sprite,
            TextureScale = new Vector2(2f, 2f),
        };

        button.OnButtonUp += _ => EggChosen?.Invoke(prototype);
        button.AddChild(tex);
        main.AddChild(button);
    }
}

public sealed class MenuButton : RadialMenuTextureButton
{
    public MenuButton()
    {

    }
}
